# Databricks notebook source
# MAGIC %md
# MAGIC ## Layer 1 silver load — task 2
# MAGIC
# MAGIC Writes the approved Keka / NetSuite table into `thoughtfocus_nsk.standardized`.
# MAGIC Adds `silver_key`. Loads the current source table. Run on a **classic cluster**.

# COMMAND ----------

from datetime import datetime as dt
import json

from pyspark.sql.functions import lit

# COMMAND ----------

# MAGIC %run "./utils/transformation_functions"

# COMMAND ----------

# MAGIC %run "./utils/etl_config_bootstrap"

# COMMAND ----------

notebook_start_time = dt.now()

# COMMAND ----------

link_key_parts = ", ".join(
    f"TRIM(COALESCE(CAST(`{c}` AS STRING), 'NA'))" if c != "source_system" else f"'{sourceSystem}'"
    for c in linkKeyColumns
)
link_key_expr = (
    f"(xxhash64(concat_ws('|', {link_key_parts})) & 9223372036854775807)"
    if link_key_parts else "CAST(NULL AS BIGINT)"
)
col_expressions_str = ",\n        ".join(build_column_expr(m, sourceSystem) for m in columnMapping)

createStagingTableQuery = f"""
SELECT
    '{sourceSystem}'  AS `source_system`,
    {link_key_expr}   AS `{linkKeyName}`,
    {col_expressions_str}
FROM {sourceCatalogName}.{sourceSchemaName}.{sourceTableName} src
"""
print(createStagingTableQuery)
staging_df = spark.sql(createStagingTableQuery)
staging_df = staging_df.withColumn("JobRun_ID", lit(JobRun_ID))
staging_df.createOrReplaceTempView(stagingTableName)

# COMMAND ----------

spark.sql(f"CREATE DATABASE IF NOT EXISTS {targetCatalogName}.{targetSchemaName}")

def get_ddl_type(mapping_entry):
    dtype = mapping_entry["data_type"].upper()
    last_tx = mapping_entry["transformations"][-1].upper()
    if last_tx in ("DATE_CAST", "DATE_JULIAN", "DATE_MMDDYY", "DATE_MMDDYYYY"):
        return "DATE"
    return dtype

ddl_cols = [f"`source_system` STRING", f"`{linkKeyName}` BIGINT"]
for m in columnMapping:
    ddl_cols.append(f"`{m['target_col']}` {get_ddl_type(m)}{sql_comment_clause(m.get('description'))}")
ddl_cols.append("`JobRun_ID` STRING")
ddl_cols.append("`TargetETLDate` TIMESTAMP")

tableCommentLiteral = sql_comment_literal(tableDescription)
tableCommentClause = f"\nCOMMENT {tableCommentLiteral}" if tableCommentLiteral else ""
CreateSqlQuery = f"""
CREATE TABLE IF NOT EXISTS {targetCatalogName}.{targetSchemaName}.{targetTableName} (
`{surrogateKeyColumnName}` BIGINT GENERATED BY DEFAULT AS IDENTITY,
{',\n'.join(ddl_cols)}
) USING DELTA{tableCommentClause}
TBLPROPERTIES ('delta.enableChangeDataFeed' = 'true')
"""
print(CreateSqlQuery)
spark.sql(CreateSqlQuery)

# COMMAND ----------

target_table_schema = spark.table(f"{targetCatalogName}.{targetSchemaName}.{targetTableName}").schema
target_table_columns = set(f"`{field.name}`" for field in target_table_schema)
staging_columns = set(f"`{column}`" for column in staging_df.columns)
new_columns = staging_columns - target_table_columns
if new_columns:
    alter_table_query = f"ALTER TABLE {targetCatalogName}.{targetSchemaName}.{targetTableName} ADD COLUMNS ("
    for c in new_columns:
        col_name = c.replace("`", "")
        col_type = staging_df.schema[col_name].dataType.simpleString().upper()
        alter_table_query += f"{c} {col_type}, "
    alter_table_query = alter_table_query.rstrip(", ") + ")"
    print(alter_table_query)
    spark.sql(alter_table_query)

# COMMAND ----------

targetCatalogPlain = targetCatalogName.strip("`")
targetSchemaPlain = targetSchemaName.strip("`")
targetTablePlain = targetTableName.strip("`")
metadataFilter = (
    f"lower(table_catalog) = {sql_string_literal(targetCatalogPlain.lower())} "
    f"AND lower(table_schema) = {sql_string_literal(targetSchemaPlain.lower())} "
    f"AND lower(table_name) = {sql_string_literal(targetTablePlain.lower())}"
)
current_table_comment = None
current_column_comments = {}
comments_readable = True
try:
    table_comment_rows = spark.sql(
        f"SELECT comment FROM {targetCatalogName}.information_schema.tables WHERE {metadataFilter}"
    ).collect()
    current_table_comment = table_comment_rows[0][0] if table_comment_rows else None
    for row in spark.sql(
        f"SELECT column_name, comment FROM {targetCatalogName}.information_schema.columns "
        f"WHERE {metadataFilter}"
    ).collect():
        current_column_comments[str(row[0]).lower()] = row[1]
except Exception as comment_read_error:
    comments_readable = False
    print(f"WARNING could not read comments ({type(comment_read_error).__name__})")

target_table_columns_now = set(
    field.name for field in spark.table(f"{targetCatalogName}.{targetSchemaName}.{targetTableName}").schema
)
comment_statements = []
if tableCommentLiteral and not (
    comments_readable
    and normalize_comment_text(current_table_comment) == normalize_comment_text(tableDescription)
):
    comment_statements.append(
        f"COMMENT ON TABLE {targetCatalogName}.{targetSchemaName}.{targetTableName} "
        f"IS {tableCommentLiteral}"
    )
for m in columnMapping + etlMetadataColumns:
    column_comment_literal = sql_comment_literal(m.get("description"))
    if not column_comment_literal or m["target_col"] not in target_table_columns_now:
        continue
    if comments_readable and (
        normalize_comment_text(current_column_comments.get(m["target_col"].lower()))
        == normalize_comment_text(m.get("description"))
    ):
        continue
    comment_statements.append(
        f"ALTER TABLE {targetCatalogName}.{targetSchemaName}.{targetTableName} "
        f"ALTER COLUMN `{m['target_col']}` COMMENT {column_comment_literal}"
    )
for comment_statement in comment_statements:
    spark.sql(comment_statement)
print(f"metadata sync: {len(comment_statements)} comment statement(s)")

# COMMAND ----------

tagFilter = (
    f"lower(catalog_name) = {sql_string_literal(targetCatalogPlain.lower())} "
    f"AND lower(schema_name) = {sql_string_literal(targetSchemaPlain.lower())} "
    f"AND lower(table_name) = {sql_string_literal(targetTablePlain.lower())}"
)
current_table_tags = None
current_column_tags = None
try:
    current_table_tags = [
        row[0] for row in spark.sql(
            f"SELECT tag_name FROM {targetCatalogName}.information_schema.table_tags WHERE {tagFilter}"
        ).collect()
    ]
    current_column_tags = {}
    for row in spark.sql(
        f"SELECT column_name, tag_name FROM {targetCatalogName}.information_schema.column_tags "
        f"WHERE {tagFilter}"
    ).collect():
        current_column_tags.setdefault(str(row[0]).lower(), []).append(row[1])
except Exception as tag_read_error:
    print(f"WARNING could not read tags ({type(tag_read_error).__name__})")

targetTableFQN = f"{targetCatalogName}.{targetSchemaName}.{targetTableName}"
table_tag_statements, table_tag_summary = tag_sync_statements(
    targetTableFQN, tableTags, current_table_tags)
for statement in table_tag_statements:
    spark.sql(statement)
print(f"tags sync: table tags — {table_tag_summary['state']}")
for m in columnMapping + etlMetadataColumns:
    col_tags = parse_tags(m.get("tags"))
    if not col_tags or m["target_col"] not in target_table_columns_now:
        continue
    col_statements, _ = tag_sync_statements(
        targetTableFQN,
        col_tags,
        None if current_column_tags is None else current_column_tags.get(m["target_col"].lower(), []),
        column=m["target_col"],
    )
    for statement in col_statements:
        spark.sql(statement)

# COMMAND ----------

spark.sql(f"DELETE FROM {targetCatalogName}.{targetSchemaName}.{targetTableName}")
staging_cols = set(f"`{c}`" for c in staging_df.columns)
columns_str = ", ".join(staging_cols)
num_inserted_rows = spark.sql(f"SELECT COUNT(*) AS cnt FROM `{stagingTableName}`").collect()[0]["cnt"]
insertIntoQuery = f"""
INSERT INTO {targetCatalogName}.{targetSchemaName}.{targetTableName} ({columns_str}, `TargetETLDate`)
SELECT {columns_str}, current_timestamp() FROM `{stagingTableName}`
"""
print(insertIntoQuery)
spark.sql(insertIntoQuery)
print(f"Rows inserted: {num_inserted_rows}")

# COMMAND ----------

spark.sql(f"""
CREATE TABLE IF NOT EXISTS {auditTableName} (
`JobRun_ID` STRING,
`source_table` STRING,
`target_table` STRING,
`notebook_start_time` TIMESTAMP,
`notebook_end_time` TIMESTAMP,
`notebook_duration_minutes` BIGINT,
`rows_inserted` BIGINT,
`rows_updated` BIGINT,
`status` STRING,
`notebook_path` STRING
) USING DELTA
TBLPROPERTIES ('delta.enableChangeDataFeed' = 'true')
""")
notebook_end_time = dt.now()
try:
    nb_path = dbutils.notebook.entry_point.getDbutils().notebook().getContext().notebookPath().get()
except Exception:
    nb_path = "unknown"
source_full = f"{sourceCatalogName}.{sourceSchemaName}.{sourceTableName}"
target_full = f"{targetCatalogName}.{targetSchemaName}.{targetTableName}"
notebook_duration_minutes = int((notebook_end_time - notebook_start_time).total_seconds() / 60)
audit_insert = f"""
INSERT INTO {auditTableName}
(JobRun_ID, source_table, target_table,
 notebook_start_time, notebook_end_time, notebook_duration_minutes,
 rows_inserted, rows_updated, status, notebook_path)
VALUES (
  '{JobRun_ID}',
  '{source_full}',
  '{target_full}',
  TIMESTAMP '{notebook_start_time.strftime("%Y-%m-%d %H:%M:%S")}',
  TIMESTAMP '{notebook_end_time.strftime("%Y-%m-%d %H:%M:%S")}',
  {notebook_duration_minutes},
  {num_inserted_rows},
  0,
  'Success',
  '{nb_path}'
)
"""
spark.sql(audit_insert)
print(f"Audit record inserted into {auditTableName}")
dbutils.notebook.exit(json.dumps({"rowsInserted": num_inserted_rows, "rowsUpdated": 0}))
